services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: kommodity
      POSTGRES_PASSWORD: kommodity
      POSTGRES_DB: kommodity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kommodity-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kommodity -d kommodity"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: kommodity@corti.ai
      PGADMIN_DEFAULT_PASSWORD: kommodity
      PGADMIN_CONFIG_SERVER_MODE: "False" # Load preconfigured servers
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - kommodity-net

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "5443:5443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - kommodity-net
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  kommodity-net:
    driver: bridge
