{{- if .Values.kommodity.clusterAutoscaler.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  labels:
    app.kubernetes.io/managed-by: kommodity
    cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  labels:
    app.kubernetes.io/managed-by: kommodity
    cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
  annotations:
    kubernetes.io/service-account.name: {{ .Release.Name }}-cluster-autoscaler
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  labels:
    app.kubernetes.io/managed-by: kommodity
    cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-cluster-autoscaler
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-cluster-autoscaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-cluster-autoscaler
  labels:
    app.kubernetes.io/managed-by: kommodity
    cluster.x-k8s.io/cluster-name: {{ .Release.Name }}
rules:
  - apiGroups: ["cluster.x-k8s.io"]
    resources:
      - clusters
      - machinedeployments
      - machinedeployments/scale
      - machines
      - machinesets
      - machinepools
      - machinepools/scale
    verbs: ["get", "list", "watch", "update", "patch"]
{{- end }}
