{{- if eq .Values.kommodity.provider.name "Kubevirt" }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  infraClusterSecretRef:
    name: {{ .Values.kommodity.provider.secret.name }}
    namespace: {{ .Release.Namespace }}
  controlPlaneServiceTemplate:
    metadata:
      namespace: {{ .Values.kommodity.provider.config.infraClusterNamespace }}
    spec:
      type: LoadBalancer
  {{- if dig "provider" "config" "controlPlaneEndpoint" "" .Values.kommodity }}
  controlPlaneEndpoint:
    host: {{ .Values.kommodity.provider.config.controlPlaneEndpoint.host }}
    port: {{ .Values.kommodity.provider.config.controlPlaneEndpoint.port }}
  {{- end }}
{{- end }}
