{{- if eq .Values.kommodity.provider.name "Kubevirt" }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.kommodity.provider.kubevirtClusterNamespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  infraClusterSecretRef:
    name: {{ .Values.kommodity.provider.secret.name }}
    namespace: {{ .Values.kommodity.provider.kubevirtClusterNamespace }}
{{- end }}
