{{- range $name, $np := .Values.kommodity.nodepools }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $.Release.Name }}-worker-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  clusterName: {{ $.Release.Name }}
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: {{ $np.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ $.Release.Name }}
        cluster.x-k8s.io/deployment-name: {{ $.Release.Name }}-worker-{{ $name }}
        app.kubernetes.io/managed-by: kommodity
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: {{ $.Release.Name }}-worker-{{ $name }}
          namespace: {{ $.Release.Namespace }}
      clusterName: {{ $.Release.Name }}
      failureDomain: {{ $np.zone }}
      infrastructureRef:
        {{- if not $.Values.kommodity.provider.name }}
        {{- fail "kommodity.provider.name must be set in values.yaml" -}}
        {{- else if eq $.Values.kommodity.provider.name "Docker" }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        {{- else if eq $.Values.kommodity.provider.name "Scaleway" }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ScalewayMachineTemplate
        {{- else if eq $.Values.kommodity.provider.name "Kubevirt" }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: KubevirtMachineTemplate
        {{- else }}
        {{- fail "infrastructure provider is not supported" -}}
        {{- end }}
        name: {{ $.Release.Name }}-worker-{{ $name }}
        {{- if eq $.Values.kommodity.provider.name "Kubevirt" }}
        namespace: {{ $.Values.kommodity.provider.kubevirtClusterNamespace }}
        {{- else }}
        namespace: {{ $.Release.Namespace }}
        {{- end }}
      version: {{ $.Values.kubernetes.version }}
{{- end }}
