{{- define "kommodity.addon.extra-values" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-extra-values
  namespace: {{ .namespace }}
stringData:
  values.yaml: |
{{- toYaml .initialExtraValues | nindent 4 }}
{{- end }}
