---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ $.Release.Name }}-controlplane
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  version: {{ $.Values.kubernetes.version }}
  replicas: {{ $.Values.kommodity.controlplane.replicas }}
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  infrastructureTemplate:
    {{- if not $.Values.kommodity.provider.name }}
    {{- fail "kommodity.provider.name must be set in values.yaml" -}}
    {{- else if eq $.Values.kommodity.provider.name "Docker" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    {{- else if eq $.Values.kommodity.provider.name "Scaleway" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ScalewayMachineTemplate
    {{- else if eq $.Values.kommodity.provider.name "Kubevirt" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtMachineTemplate
    {{- else }}
    {{- fail "infrastructure provider is not supported" -}}
    {{- end }}
    name: {{ $.Release.Name }}-controlplane
    namespace: {{ .Release.Namespace }}
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: {{ include "kommodity.talosVersion" $ }}
      hostname: {}
    init:
      generateType: init
      hostname: {}
