{{- $anyAddonEnabled := false }}
{{- if .Values.kommodity.addons -}}
{{- range $name, $addon := .Values.kommodity.addons }}
  {{- if $addon.enabled }}
    {{- $anyAddonEnabled = true }}
  {{- end }}
{{- end }}
{{- end }}

{{/*
Output inline manifest items for enabled addons as YAML text.
This preserves proper YAML block scalar formatting for multi-line contents.
*/}}
{{- define "kommodity.addonsInlineManifests" -}}
{{- $root := . -}}
{{- range $name, $addon := $root.Values.kommodity.addons }}
{{- if $addon.enabled }}
  {{- $contents := "" }}
  {{- if $addon.manifest }}
    {{- $contents = tpl $addon.manifest $root }}
  {{- else }}
    {{- $addonTemplateName := printf "kommodity.addon.%s" $name }}
    {{- if hasKey $.Template $addonTemplateName }}
      {{- $contents = include $addonTemplateName $root }}
    {{- else }}
      {{- $contents = "" }}
    {{- end }}
    {{- if $addon.initialExtraValues }}
- name: {{ $name }}-extra-values
  contents: |
{{ include "kommodity.addon.extra-values" (dict
  "name"               $name
  "namespace"          (default .name $addon.namespace)
  "initialExtraValues" $addon.initialExtraValues
) | indent 4 }}
    {{- end }}
    {{- if $addon.namespace }}
- name: {{ $name }}-namespace
  contents: |
{{ include "kommodity.addon.namespace" (dict
  "namespace"  $addon.namespace
) | indent 4 }}
    {{- end }}
{{- if $contents }}
- name: {{ $name }}
  contents: |
{{ $contents | indent 4 }}
{{- end }}
- name: {{ $name }}-installer
  contents: |
{{ include "kommodity.addon.installer" (dict
  "name"  $name
  "addon" $addon
) | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ $.Release.Name }}-controlplane
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  {{- if and (hasKey .Values.kommodity.controlplane "kubernetes") (hasKey .Values.kommodity.controlplane.kubernetes "version") }}
  version: {{ $.Values.kommodity.controlplane.kubernetes.version }}
  {{- else }}
  version: {{ $.Values.kubernetes.version }}
  {{- end }}
  replicas: {{ $.Values.kommodity.controlplane.replicas }}
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  infrastructureTemplate:
    {{- if not $.Values.kommodity.provider.name }}
    {{- fail "kommodity.provider.name must be set in values.yaml" -}}
    {{- else if eq $.Values.kommodity.provider.name "Docker" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    {{- else if eq $.Values.kommodity.provider.name "Scaleway" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ScalewayMachineTemplate
    {{- else if eq $.Values.kommodity.provider.name "Kubevirt" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtMachineTemplate
    {{- else }}
    {{- fail "infrastructure provider is not supported" -}}
    {{- end }}
    name: {{ .Release.Name }}-controlplane-{{ include "kommodity-cluster.machineSpecsHash" (dict "poolValues" .Values.kommodity.controlplane "allValues" .Values) }}
    namespace: {{ $.Release.Namespace }}
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: {{ default (include "kommodity.talosVersion" $) (dig "talos" "version" "" $.Values.kommodity.controlplane) }}
      hostname: {}
      {{- $cp := $.Values.kommodity.controlplane }}
      {{- $cpPatches := dig "configPatches" nil $cp }}
      {{- $globalPatches := dig "global" "configPatches" nil $.Values.kommodity }}
      {{- $cpTaints := dig "taints" nil $cp }}
      {{- $cpLabels := dig "labels" nil $cp }}
      {{- $cpAnnotations := dig "annotations" nil $cp }}
      {{- $disableTalosNetwork := or $.Values.talos.disableCNI $.Values.talos.disableKubeProxy }}
      {{- $oidc := dig "oidc" nil $.Values.kommodity }}
      {{- $oidcEnabled := and $oidc $oidc.enabled }}
      {{- $hasExtraConfigPatches := or $cpPatches $globalPatches $cpTaints $cpLabels $cpAnnotations $oidcEnabled }}
      {{- /* Check if user has /cluster/inlineManifests in global.configPatches */ -}}
      {{- $userInlineManifests := list }}
      {{- range $globalPatches }}
        {{- if and (eq .op "add") (eq .path "/cluster/inlineManifests") }}
          {{- $userInlineManifests = .value }}
        {{- end }}
      {{- end }}
      {{- $hasInlineManifests := or $anyAddonEnabled (gt (len $userInlineManifests) 0) }}
      {{- if or $hasInlineManifests $hasExtraConfigPatches $disableTalosNetwork $.Values.talos.installer $.Values.kommodity.logLevel }}
      configPatches:
      {{- end }}
      {{- /* Output /cluster/inlineManifests patch with merged addon + user manifests */ -}}
      {{- if $hasInlineManifests }}
        - op: add
          path: /cluster/inlineManifests
          value:
      {{- if $anyAddonEnabled }}
{{- include "kommodity.addonsInlineManifests" . | trim | nindent 12 }}
      {{- end }}
      {{- range $userInlineManifests }}
            - name: {{ .name }}
              contents: |
{{ .contents | indent 16 }}
      {{- end }}
      {{- end }}
      {{- /* Output other patches (excluding /cluster/inlineManifests which is handled above) */ -}}
      {{- if or $hasExtraConfigPatches $.Values.talos.installer $.Values.kommodity.logLevel }}
{{- include "kommodity-cluster.combinedConfigPatches" (dict "globalConfigPatches" $globalPatches "nodepoolConfigPatches" $cpPatches "taints" $cpTaints "labels" $cpLabels "annotations" $cpAnnotations "oidc" $oidc "installer" $.Values.talos.installer "logLevel" $.Values.kommodity.logLevel) | trim | nindent 8 }}
      {{- end }}
      {{- if $.Values.talos.disableCNI }}
      {{- include "kommodity.talos.cni.disable" . | nindent 8 }}
      {{- end }}
      {{- if $.Values.talos.disableKubeProxy }}
      {{- include "kommodity.talos.proxy.disable" . | nindent 8 }}
      {{- end }}
      {{- if $.Values.kommodity.provider.cloudControllerManager.enabled }}
      {{- include "kommodity.talos.ccm" (dict "manifest" $.Values.kommodity.provider.cloudControllerManager.manifest) | nindent 8 }}
      {{- end }}
    {{- if or $.Values.kommodity.kms.enabled (not $.Values.kommodity.network.ipv4.public) $.Values.talos.autoBootstrap.enabled $.Values.kommodity.security.enabled }}
      strategicPatches:
    {{- if $.Values.kommodity.kms.enabled }}
    {{- /* Use VolumeConfig for disk encryption (Talos v1.12+) instead of deprecated machine.systemDiskEncryption */}}
{{- include "kommodity.talos.volumeEncryption" (dict "endpoint" $.Values.kommodity.kms.endpoint) | nindent 8 }}
    {{- end }}
    {{- if or (not $.Values.kommodity.network.ipv4.public) $.Values.talos.autoBootstrap.enabled }}
    {{- /* ExtensionServiceConfig for kommodity-autobootstrap extension */}}
{{- include "kommodity.talos.autoBootstrapExtensionServiceConfig" (dict "autoBootstrap" $.Values.talos.autoBootstrap "logLevel" $.Values.kommodity.logLevel) | nindent 8 }}
    {{- end }}
    {{- if $.Values.kommodity.security.enabled }}
    {{- /* ExtensionServiceConfig for kommodity-attestation extension */}}
{{- include "kommodity.talos.attestationExtensionServiceConfig" (dict "logLevel" $.Values.kommodity.logLevel) | nindent 8 }}
    {{- end }}
    {{- end }}
