{{- $anyAddonEnabled := false }}
{{- if .Values.kommodity.addons -}}
{{- range $name, $addon := .Values.kommodity.addons }}
  {{- if $addon.enabled }}
    {{- $anyAddonEnabled = true }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "kommodity.addonsInlineManifests" -}}
{{- $root := . -}}
{{- range $name, $addon := $root.Values.kommodity.addons }}
{{- if $addon.enabled }}
  {{- $contents := "" }}
  {{- if $addon.manifest }}
    {{- $contents = tpl $addon.manifest $root }}
  {{- else }}
    {{- $contents = include (printf "kommodity.addon.%s" $name) $root }}
    {{- if $addon.namespace }}
- name: {{ $name }}-namespace
  contents: |
{{ include "kommodity.addon.namespace" (dict
  "namespace"  $addon.namespace
) | indent 4 }}
    {{- end }}
- name: {{ $name }}
  contents: |
{{ $contents | indent 4 }}
- name: {{ $name }}-installer
  contents: |
{{ include "kommodity.addon.installer" (dict
  "name"  $name
  "addon" $addon
) | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ $.Release.Name }}-controlplane
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  version: {{ $.Values.kubernetes.version }}
  replicas: {{ $.Values.kommodity.controlplane.replicas }}
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  infrastructureTemplate:
    {{- if not $.Values.kommodity.provider.name }}
    {{- fail "kommodity.provider.name must be set in values.yaml" -}}
    {{- else if eq $.Values.kommodity.provider.name "Docker" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    {{- else if eq $.Values.kommodity.provider.name "Scaleway" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ScalewayMachineTemplate
    {{- else if eq $.Values.kommodity.provider.name "Kubevirt" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtMachineTemplate
    {{- else }}
    {{- fail "infrastructure provider is not supported" -}}
    {{- end }}
    name: {{ $.Release.Name }}-controlplane
    namespace: {{ $.Release.Namespace }}
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: {{ include "kommodity.talosVersion" $ }}
      hostname: {}
      {{- if $anyAddonEnabled }}
      configPatches:
        - op: add
          path: /cluster/inlineManifests
          value:
            - name: kommodity-system
              contents: |
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: kommodity-system
                  labels:
                    pod-security.kubernetes.io/enforce: privileged
                    pod-security.kubernetes.io/enforce-version: latest
                ---
{{- include "kommodity.addonsInlineManifests" . | trim | nindent 12 }}
      {{- end }}
    init:
      generateType: init
      hostname: {}
