{{- $anyAddonEnabled := false }}
{{- if .Values.kommodity.addons -}}
{{- range $name, $addon := .Values.kommodity.addons }}
  {{- if $addon.enabled }}
    {{- $anyAddonEnabled = true }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "kommodity.addonsInlineManifests" -}}
{{- $root := . -}}
{{- range $name, $addon := $root.Values.kommodity.addons }}
{{- if $addon.enabled }}
  {{- $contents := "" }}
  {{- if $addon.manifest }}
    {{- $contents = tpl $addon.manifest $root }}
  {{- else }}
    {{- $addonTemplateName := printf "kommodity.addon.%s" $name }}
    {{- if hasKey $.Template $addonTemplateName }}
      {{- $contents = include $addonTemplateName $root }}
    {{- else }}
      {{- $contents = "" }}
    {{- end }}
    {{- if $addon.initialExtraValues }}
- name: {{ $name }}-extra-values
  contents: |
{{ include "kommodity.addon.extra-values" (dict
  "name"               $name
  "namespace"          (default .name $addon.namespace)
  "initialExtraValues" $addon.initialExtraValues
) | indent 4 }}
    {{- end }}
    {{- if $addon.namespace }}
- name: {{ $name }}-namespace
  contents: |
{{ include "kommodity.addon.namespace" (dict
  "namespace"  $addon.namespace
) | indent 4 }}
    {{- end }}
{{- if $contents }}
- name: {{ $name }}
  contents: |
{{ $contents | indent 4 }}
{{- end }}
- name: {{ $name }}-installer
  contents: |
{{ include "kommodity.addon.installer" (dict
  "name"  $name
  "addon" $addon
) | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: {{ $.Release.Name }}-controlplane
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: kommodity
spec:
  {{- if and (hasKey .Values.kommodity.controlplane "kubernetes") (hasKey .Values.kommodity.controlplane.kubernetes "version") }}
  version: {{ $.Values.kommodity.controlplane.kubernetes.version }}
  {{- else }}
  version: {{ $.Values.kubernetes.version }}
  {{- end }}
  replicas: {{ $.Values.kommodity.controlplane.replicas }}
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  infrastructureTemplate:
    {{- if not $.Values.kommodity.provider.name }}
    {{- fail "kommodity.provider.name must be set in values.yaml" -}}
    {{- else if eq $.Values.kommodity.provider.name "Docker" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    {{- else if eq $.Values.kommodity.provider.name "Scaleway" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ScalewayMachineTemplate
    {{- else if eq $.Values.kommodity.provider.name "Kubevirt" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KubevirtMachineTemplate
    {{- else }}
    {{- fail "infrastructure provider is not supported" -}}
    {{- end }}
    name: {{ .Release.Name }}-controlplane-{{ include "kommodity-cluster.machineSpecsHash" (dict "poolValues" .Values.kommodity.controlplane "allValues" .Values) }}
    namespace: {{ $.Release.Namespace }}
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: {{ default (include "kommodity.talosVersion" $) (dig "talos" "version" "" $.Values.kommodity.controlplane) }}
      hostname: {}
      {{- $cp := $.Values.kommodity.controlplane }}
      {{- $cpPatches := dig "configPatches" nil $cp }}
      {{- $globalPatches := dig "global" "configPatches" nil $.Values.kommodity }}
      {{- $cpTaints := dig "taints" nil $cp }}
      {{- $cpLabels := dig "labels" nil $cp }}
      {{- $cpAnnotations := dig "annotations" nil $cp }}
      {{- $disableTalosNetwork := or $.Values.talos.disableCNI $.Values.talos.disableKubeProxy }}
      {{- $oidcEnabled := and (hasKey $.Values.kommodity "oidc") $.Values.kommodity.oidc.enabled }}
      {{- $hasExtraConfigPatches := or $cpPatches $globalPatches $cpTaints $cpLabels $cpAnnotations }}
      {{- if or $anyAddonEnabled $hasExtraConfigPatches $disableTalosNetwork $oidcEnabled }}
      configPatches:
      {{- end }}
        - op: add
          path: /cluster/inlineManifests
          value:
      {{- if $anyAddonEnabled }}
{{- include "kommodity.addonsInlineManifests" . | trim | nindent 12 }}
      {{- end }}
      {{- if $hasExtraConfigPatches }}
{{- include "kommodity-cluster.combinedConfigPatches" (dict "globalConfigPatches" $globalPatches "nodepoolConfigPatches" $cpPatches "taints" $cpTaints "labels" $cpLabels "annotations" $cpAnnotations) | trim | nindent 8 }}
      {{- end }}
      {{- if $.Values.talos.disableCNI }}
      {{- include "kommodity.talos.cni.disable" . | nindent 8 }}
      {{- end }}      
      {{- if $.Values.talos.disableKubeProxy }}
      {{- include "kommodity.talos.proxy.disable" . | nindent 8 }}
      {{- end }}
      {{- if $.Values.kommodity.provider.cloudControllerManager.enabled }}
      {{- include "kommodity.talos.ccm" (dict "manifest" $.Values.kommodity.provider.cloudControllerManager.manifest) | nindent 8 }}
      {{- end }}
      {{- if $oidcEnabled }}
      {{- include "kommodity.talos.oidc" (dict "oidc" $.Values.kommodity.oidc) | nindent 8 }}
      {{- end }}
    {{- if $.Values.kommodity.kms.enabled }}
    {{- /* Use VolumeConfig for disk encryption (Talos v1.12+) instead of deprecated machine.systemDiskEncryption */}}
    strategicPatches:
{{- include "kommodity.talos.volumeEncryption" (dict "endpoint" $.Values.kommodity.kms.endpoint) | nindent 6 }}
    {{- end }}
